SET LINESIZE 200
SET PAGESIZE 100
SET TRIMSPOOL ON
SET TAB OFF
SET FEEDBACK ON
SET VERIFY OFF
SET ECHO OFF

COLUMN banner_full FORMAT A90
COLUMN version_full FORMAT A20
COLUMN instance_name FORMAT A15
COLUMN host_name FORMAT A25
COLUMN name FORMAT A35
COLUMN value FORMAT A80
COLUMN open_mode FORMAT A15
COLUMN database_role FORMAT A15
COLUMN comp_id FORMAT A15
COLUMN status FORMAT A12
COLUMN owner FORMAT A25
COLUMN network_name FORMAT A35
COLUMN pdb FORMAT A15
